### ISSUE TITLE
problems running on CentOS 7 and Ubuntu 16.04

### ISSUE THREAD

**Issue by glaucoaq** [dkfi/docker-oracle-xe-10g#3]
Hi. First of all, thanks for work. Since Oracle removed 10g XE from available downloads, this is the best way to get it up and running.

However, it didn't work as expected - at least for me. I've followed the steps religiously - pulled docker image, ran the provided command line verbatim - and I'm able to access the running image via SSH, but neither SQLPLUS nor HTTPS is available.

I've tested on Ubuntu 16.04 and CentOS 7 with same results.
ORACLE:
```
sqlplus64 system/oracle@localhost:49161/xe
SQL*Plus: Release 12.2.0.1.0 Production on Mon Mar 5 18:37:22 2018
Copyright (c) 1982, 2016, Oracle.  All rights reserved.
ERROR:
ORA-12514: TNS:listener does not currently know of service requested in connect
descriptor
```
APEX:
```
curl http://localhost:49162/apex
curl: (56) Recv failure: Connection reset by peer
```

Could you please help?

**Comment by dkfi** [comment]
Hi @glaucoaq ! Sorry for getting back to you so late. Apparently something is wrong with my notifications. I've also only noticed just now that docker hub has removed discussions on the image page. There used to be a conversation there between me and other people who have had the same issue. To get it to work just build the image from this repo... don't use the one from docker hub directly. I still haven't found out the reason behind this weird behaviour. I will try pushing a newly built image but I'm sure I did try this already a couple of years ago. Let me know if that worked out well.

**Comment by dkfi** [comment]
OK. I've just pushed a newly built docker image onto docker hub. Could you please test it and see if that runs correctly for you too. I removed the push-to-build github-dockerhub integration and my manually pushed image seems to work now. Let me know.

**Comment by dkfi** [comment]
I'm closing this issue because it was related to #4

**Comment by glaucoaq** [comment]
Hi @dkfi . It seems to be working not. I was able to create a container and connect using SQLPlus.

Thanks a lot!!!
