### ISSUE TITLE
Not able to connect to oracle DB

### ISSUE THREAD

**Issue by abhikur** [dkfi/docker-oracle-xe-10g#5]
Hi,
I am running this oralce image on mac with port 8080 forwarded. When the container is up is shows some error (fail to unregister for HTTP port using xdb configuration) and thus I cannot access the oracle DB from the browser. But when I quit the container and start it again then I am able to access the DB from the browser. I want to run this container as a service using docker-compose and thus I want that this DB container should be up and running at the first time itself. Please assist me on this. 
Thanks in advance

**Comment by dkfi** [comment]
Hi @abhikur,

What do you mean by port 8080 forwarded? If you've run the project as described in the README using
```bash
docker run -d -p 49160:22 -p 49161:1521 -p 49162:8080 dkfi/docker-oracle-xe-10g
```
You should be able to access the it through:
```
http://localhost:49162/apex
```
About your docker-compose issue, I'm not quite sure I understood what you meant. If you are trying to get the container to run automatically at boot you need to use "restart: always" key.

Please be more specific when asking questions and provide actual error messages to ease the whole process. Thanks.

**Comment by abhikur** [comment]
Hi Kristian,

I was able to run the container but for that, I had to change the script a
little bit. The commands for running the Oracle server were not working
fine on my mac. I have the scripts with me. If you want I can send it to
you so that you can see what I have done.

**Comment by dkfi** [comment]
Hi @abhikur,

Sure! I'd be happy to see your changes. It would be easier if you could send me a PR instead :wink:

**Comment by abhikur** [comment]
Hi Kristian,
So what I did was, created a setup.sh seperate file and moves the server
start code there and put a sleep after the oracle-xe start. Why, because
the listner was breaking (su -c "$ORACLE_HOME/bin/lsnrctl start" oracle).
But after some more investigation I found that the listner is already
started when you start oracle-xe. So the only change need to do is remove
the listner start line (su -c "$ORACLE_HOME/bin/lsnrctl start" oracle). Now
the Dockerfile should look like this:

FROM debian:wheezy

MAINTAINER Kristian Du <kristian.du@gmail.com>

ENV ORACLE_HOME=/usr/lib/oracle/xe/app/oracle/product/10.2.0/server
ENV LD_LIBRARY_PATH=$ORACLE_HOME/lib
ENV PATH=$ORACLE_HOME/bin:$PATH
ENV ORACLE_SID=XE

ADD oracle-xe_10.2.0.1-1.1_i386.debaa /
ADD oracle-xe_10.2.0.1-1.1_i386.debab /
ADD oracle-xe_10.2.0.1-1.1_i386.debac /

RUN dpkg --add-architecture i386 && \
    apt-get update && apt-get install -y \
       bc:i386 \
       libaio1:i386 \
       libc6-i386 \
       net-tools \
       openssh-server && \
    apt-get clean && \
    mkdir /var/run/sshd && \
    echo 'root:admin' | chpasswd && \
    sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/'
/etc/ssh/sshd_config && \
    sed 's@session\s*required\s*pam_loginuid.so@session optional
pam_loginuid.so@g' -i /etc/pam.d/sshd && \
    echo "export VISIBLE=now" >> /etc/profile && \
    cat /oracle-xe_10.2.0.1-1.1_i386.deba* >
/oracle-xe_10.2.0.1-1.1_i386.deb && \
    dpkg -i /oracle-xe_10.2.0.1-1.1_i386.deb && \
    rm /oracle-xe_10.2.0.1-1.1_i386.deb* && \
    printf 8080\\n1521\\noracle\\noracle\\ny\\n |
/etc/init.d/oracle-xe configure && \
    echo 'export
ORACLE_HOME=/usr/lib/oracle/xe/app/oracle/product/10.2.0/server' >>
/etc/bash.bashrc && \
    echo 'export LD_LIBRARY_PATH=$ORACLE_HOME/lib' >> /etc/bash.bashrc && \
    echo 'export PATH=$ORACLE_HOME/bin:$PATH' >> /etc/bash.bashrc && \
    echo 'export ORACLE_SID=XE' >> /etc/bash.bashrc

EXPOSE 1521 22 8080

CMD sed -i -E "s/HOST = [^)]+/HOST = $HOSTNAME/g"
/usr/lib/oracle/xe/app/oracle/product/10.2.0/server/network/admin/listener.ora;
\
    sed -i -E "s/HOST = [^)]+/HOST = $HOSTNAME/g"
/usr/lib/oracle/xe/app/oracle/product/10.2.0/server/network/admin/tnsnames.ora;
\
    service oracle-xe start; \
    echo "alter system disable restricted session;" | sqlplus -s
SYSTEM/oracle; \
    echo "EXEC DBMS_XDB.SETLISTENERLOCALACCESS(FALSE);" | sqlplus -s
SYSTEM/oracle; \
    /usr/sbin/sshd -D

**Comment by dkfi** [comment]
@abhikur ... I think the problem you encountered has to do with dynamic instance registration with the listener. Our listener.ora file is configured to allow for dynamic registration. Have you tried waiting 10 to 20 seconds before trying to connect to the database. Dynamic registration sometimes takes longer than expected.

**Comment by abhikur** [comment]
Yes, you are right I tried with wait for 10 seconds and it worked. It takes
some time to start the service and therefore I had to put sleep for 10 sec
to connect to DB.
